Update Chart to 2.5.0
conduktor/conduktor-public-charts pull request #50
Opened 2024-01-22 14:28 UTC by Stu-conduktor

2024-01-22 14:28 UTC, Stu-conduktor commented
@fteychene - is it as simple as this or more places to update?

2024-01-22 16:39 UTC, qboileau requested changes
Missing image tag update in [values.yaml](https://github.com/conduktor/conduktor-public-charts/blob/main/charts/gateway/values.yaml#L24) and in [readme](https://github.com/conduktor/conduktor-public-charts/blob/main/charts/gateway/README.md?plain=1#L28) otherwise 2.5.0 chart will still deploy 2.4.0 gateway image

2024-01-22 16:41 UTC, Stu-conduktor commented
@qboileau -do you mind making the changes on this branch? I can then use this as a reference for each release moving forward.

2024-01-23 13:34 UTC, framiere approved these changes

2024-01-23 14:50 UTC, merged